# Add application configuration variables here, as shown below.
#

DEVELOPER_NAME:

api_shared_secret:
app_name: Statisfy
app_store_id: 918625793

AWS_ACCESS_KEY: AKIAIN5Q6OH423Q7PHJQ
AWS_SECRET_ACCESS_KEY: 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
AWS_REGION: us-east-1
AWS_BUCKET: crashmob-production

TWILIO_SID: ACdafefacb4838c29e007d7774518deb49
TWILIO_AUTH_TOKEN: 08563af4fa237873b5143023d2896a9c
TWILIO_FROM: 6179823804

DEVICE_AWS_ACCESS_KEY: AKIAIN5Q6OH423Q7PHJQ
DEVICE_AWS_SECRET_ACCESS_KEY: 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
DEVICE_AWS_REGION: us-east-1
DEVICE_AWS_BUCKET: crashmob-production

development:
  AWS_BUCKET: crashmob-development
  DEVICE_AWS_BUCKET: crashmob-development

staging:
  AWS_BUCKET: crashmob-labs
  DEVICE_AWS_BUCKET: crashmob-labs
